### ISSUE TITLE
Uncaught Error: supabaseUrl is required.

### ISSUE THREAD

**Issue by tchiks1** [Stamm-Silberfuchse/sms-frontend#1]
When i launch app with npm install && npm run dev, i have in console of navigator an error "Uncaught Error: supabaseUrl is required."
how to pass resolve this error

**Comment by jomichaelis** [comment]
To connect the app with a database, either set up your own supabase instance or create one in the supabase.com dashboard.
After that, you will see two keys in your overview of Supabase.
The Supabase URL and the Supabase Anon Key.
Copy both keys into a file called ".env":
========
VITE_SUPABASE_URL=https://<<bliblablub>>.supabase.co
VITE_SUPABASE_ANON_KEY=<<very long safe key>>
========

With this, your frontend-app can connect to the backend server (Supabase).

Be aware that this project is still in an early stage of development.
Commands how to set up supabase will be added as soon as the project reaches v1.0.0
